### ISSUE TITLE
Retrieve the AWSCredentials from the Storage in S3FileSigner

### ISSUE THREAD

**Issue by matar993** [agile-lab-dev/whitefox#101]

**Comment by tmnd1991** [comment]
I think this can be closed as it's already implemented: https://github.com/agile-lab-dev/whitefox/blob/ba9394e8d44b18884689a95861ec8ba5b32fa899/server/core/src/main/java/io/whitefox/core/services/FileSignerFactoryImpl.java#L22

**Comment by tmnd1991** [comment]
up
