### ISSUE TITLE
version and files returned by "query" api might not match

### ISSUE THREAD

**Issue by tmnd1991** [agile-lab-dev/whitefox#197]
Version is retrieved here:
https://github.com/agile-lab-dev/whitefox/blob/20a0765f83d12991711e36220facabb0a4f23071/server/app/src/main/java/io/whitefox/api/deltasharing/server/DeltaSharesApiImpl.java#L195

taking into account only the starting timestamp, while the query is performed ignoring the starting timestamp and passing the query request https://github.com/agile-lab-dev/whitefox/blob/20a0765f83d12991711e36220facabb0a4f23071/server/app/src/main/java/io/whitefox/api/deltasharing/server/DeltaSharesApiImpl.java#L198

This might definitely lead to an inconsistency between version and data returned

**Comment by duhizjame** [comment]
I am a bit lost; doesn't the query request also take in account the startingTimestamp (or version)?
so the issue arrises if you do a getTableVersion on a startingTimestamp, but a queryTable without it? shouldnt this be taken care by the client? ie. the internal calls should be with the same params, once you pass into spark.options(timestamp)

**Comment by agilelab-tmnd1991** [comment]
the query request has a version, startingVersion and endingVersion fields (not all together != null), the startingTimestamp was never part of the protocol, we completely made that up :) I double checked the original delta-sharing protocol 😛
