### ISSUE TITLE
Publish container image of the server during CI

### ISSUE THREAD

**Issue by tmnd1991** [agile-lab-dev/whitefox#84]
See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by duhizjame** [comment]
can we borrow the nessie system for publishing directly? seems like it is configured for general quarkus app usage

**Comment by tmnd1991** [comment]
sure, I did not look in-depth at what Nessie does. But we already have a way of building an image thanks to quarkus.
